llm:
  api_type: "deepseek"
  model: "deepseek-reasoner"
  base_url: "https://api.deepseek.com/v1"
  api_key: "sk-4da57d72282f44a6be1a8ceff263441b"
  # Remove any proxy settings if they exist

# Enable JSON repair functionality
repair_llm_output: true
